include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
  exclude:
    - build/**
    - tool/quality/fixtures/**
    - web/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_unnecessary_containers: true
    cascade_invocations: true
    directives_ordering: true
    discarded_futures: true
    omit_local_variable_types: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_expression_function_bodies: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sized_box_for_whitespace: true
    sort_constructors_first: true
    unawaited_futures: true
    unnecessary_lambdas: true
